[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs_18"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
